### ISSUE TITLE
Can U provide some documentation ?? + screen

### ISSUE THREAD

**Issue by Diaskhan** [jablko359/BpmnEditor#1]
This is bpmn edtor.
But is save files to xpdl, not bpmn standart

![screen1](https://user-images.githubusercontent.com/15046677/31085469-050eb25e-a7b9-11e7-8d8c-c308c624e7eb.png)

**Comment by jablko359** [comment]
Hi. The main purpose was to create graphical BPMN editor that can import and export files to xpdl standard, so yes it supports only xpdl file format. It was created at AGH Univeristy of Science as some form of final project as research if "Can It be done?" and I don't with it will be developed furthermore.
